### ISSUE TITLE
Default port used is assigned to another exporter

### ISSUE THREAD

**Issue by NightTsarina** [hikhvar/mqtt2prometheus#28]
Hi,

It seems this exporter would use port 9641, but according to https://github.com/prometheus/prometheus/wiki/Default-port-allocations, that port is reserved for the CoTURN exporter.

**Comment by hikhvar** [comment]
I will check why this duplication exists. When I added this exporter to the prometheus exporter documentation in January, this port was free. I remember to allocate that port for this exporter in the wiki.

**Comment by hikhvar** [comment]
So I had a look at the git history of https://github.com/prometheus/prometheus/wiki/Default-port-allocations.

In commit 60c661b7a1d662b18a6da2c11f2de1392306edd0 I allocated the port 9641 to this exporter. 
However this commit: 568bc94f8d15c122bf1e1642a7ffb850886087b8 set a lot of ports to "FREE" including the port 9641. Which was later allocated by CoTURN. Will open a issue in the prometheus project to raise this issue to the greater community.

**Comment by hikhvar** [comment]
Btw: Thank you for packaging this project in debian unstable :star_struck:! @NightTsarina

**Comment by NightTsarina** [comment]
> Btw: Thank you for packaging this project in debian unstable star_struck! @NightTsarina

You're welcome! It will soon be part of the next stable release too (bullseye)! So, if you want to get any fixes/improvements in, you still have a couple of weeks before we enter the deep freeze. Just give me a shout so I make sure to update the Debian package

**Comment by hikhvar** [comment]
The latest v0.1.5 contains a new feature, enabling the user to have a single metric value per topic. I have to do the docs for this feature, but the details can be found in this PR: #26. I think debian users will benefit from this feature in the upcoming years.
I know, the versioning (v0.1.5 instead of v0.2.0) is a minor fuckup regarding semantic versioning. If you want to have that fixed, give me a shout.

**Comment by hikhvar** [comment]
I will close this issue. The prometheus wiki page incident was a single time issue. I raised the issue in the prometheus project. Some other ports are allocated to two exporters. Since the CoTURN and MQTT are very distinct use cases. A port collision on the same IP are very unlikely. Hence I will keep the current port to not break the setups of the users.
